name: 'E2E'
description: 'Run E2E tests'

inputs:
  status_api_key:
    description: 'API key to read job status'
    required: true
  nais_management_project_id:
    description: 'Project ID for nais/logins'
    required: false
  nais_workload_identity_provider:
    description: 'Identity provider for nais/login'
    required: false
  e2e_tag:
    description: 'Tag for E2E image'
    required: false
    default: 'latest'

branding:
  icon: 'shield'
  color: 'green'

outputs:
  image:
    description: 'E2E image'
    value: ${{ steps.image.outputs.image }}
  status:
    description: 'E2E job status'
    value: ${{ steps.status.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Checkout E2E
      uses: actions/checkout@v6
      with:
        repository: navikt/kabal-e2e-tests
        ref: ${{ inputs.e2e_tag }}

    - name: Get image registry
      id: image-registry
      uses: nais/login@v0
      with:
        team: klage

    - name: Generate UUID
      id: uuid
      shell: bash
      run: echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT

    - name: Get image tag
      id: image-tag
      shell: bash
      run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Generate image name
      id: image
      shell: bash
      run: echo "image=${{ steps.image-registry.outputs.registry }}/kabal-e2e-tests:${{ steps.image-tag.outputs.tag }}" >> $GITHUB_OUTPUT

    - name: Run E2E tests
      uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: dev-gcp
        VAR: jobid=${{ steps.uuid.outputs.uuid }},image=${{ steps.image.outputs.image }},version=${{ steps.image-tag.outputs.tag }},github_actor=${{ github.actor }},github_repository=${{ github.repository }}
        TEAM: klage
        RESOURCE: nais/e2e-job.yaml

    - name: Check E2E job status
      id: status
      uses: navikt/klage-job-status/action@main
      with:
        api_key: ${{ inputs.status_api_key }}
        job_id: ${{ steps.uuid.outputs.uuid }}
        fail: true
        fail_on_unknown: true
