apiVersion: batch/v1
kind: Job
metadata:
  labels:
    team: klage
    e2e: kabal
  name: kabal-e2e-tests-{{jobid}}
  namespace: klage
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kabal-e2e
          image: {{image}}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
      imagePullSecrets:
        - name: gpr-credentials
      restartPolicy: Never
