apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: klage
    e2e: kabal
  name: kabal-e2e-tests-{{jobid}}
  namespace: klage
spec:
  readiness:
    failureThreshold: 1
    initialDelay: 1
    path: /isready
    port: 8080
  liveness:
    failureThreshold: 1
    initialDelay: 1
    periodSeconds: 1
    path: /isalive
    port: 8080
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 8000m
      memory: 8Gi  
  backoffLimit: 0
  concurrencyPolicy: Forbid 
  image: {{image}}
  envFrom:
  - secret: kabal-e2e-test-users
  - secret: slack-e2e-secrets
  - configmap: slack-e2e-configmap
  accessPolicy:
    outbound:
      external:
      - host: kabal.intern.dev.nav.no
