apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: kabal-e2e-tests
    team: klage
  name: kabal-e2e-tests
  namespace: klage
spec:
  podSelector:
    matchLabels:
      app: kabal-frontend  
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: kabal-e2e-tests   
          namespaceSelector:
            matchLabels:
              name: klage           
  policyTypes:
    - Ingress
