apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: kabal-e2e-tests-{{jobid}}
  namespace: klage
  labels:
    team: klage
    e2e: kabal
    job_id: {{jobid}}
spec:
  ttl: 11m
  backoffLimit: 0
  concurrencyPolicy: Forbid
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 8000m
      memory: 8Gi
  image: {{image}}
  env:
    - name: JOB_ID
      value: '{{jobid}}'
    - name: VERSION
      value: '{{version}}'
    - name: GITHUB_ACTOR
      value: '{{github_actor}}'
    - name: GITHUB_REPOSITORY
      value: '{{github_repository}}'
  envFrom:
    - secret: kabal-e2e-test-users
    - secret: slack-e2e-secrets
    - configmap: slack-e2e-configmap
    - secret: klage-job-status-write-api-key
  accessPolicy:
    outbound:
      external:
        - host: kabal.intern.dev.nav.no
