apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: klage
    e2e: kabal
  name: kabal-e2e-tests-{{jobid}}
  namespace: klage
spec:
  backoffLimit: 0
  concurrencyPolicy: Forbid
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 8000m
      memory: 8Gi  
  image: {{image}}
  env:
    - name: JOB_ID
      value: {{jobid}}
  envFrom:
    - secret: kabal-e2e-test-users
    - secret: slack-e2e-secrets
    - configmap: slack-e2e-configmap
  accessPolicy:
    outbound:
      external:
        - host: kabal.intern.dev.nav.no
